version: '3'
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.4.1
    container_name: mlflow
    ports:
      - "50000:5000"
    volumes:
      - ./mlflow:/mlflow
    command: mlflow server --backend-store-uri sqlite:///mlflow/mlflow.db --host 0.0.0.0 --port 5000 --artifacts-destination /mlflow/artifacts